import 'package:flame/game.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import '../controller/shuffle_controller.dart';
import 'flame_suffle_tile.dart';

class FlameShuffle extends FlameGame {
  late final ShuffleController controller;

  @override
  Color backgroundColor() => Colors.orange;

  @override
  Future<void> onLoad() async {
    controller = Get.find<ShuffleController>();
    controller.game = this;
    newGame();
  }

  void newGame() {
    for (var child in children) {
      if (child is FlameShuffleTile) {
        remove(child);
      }
    }

    //add tiles generated by controller
    for (var tile in controller.tiles) {
      add(tile);
    }
  }
}
